# Generated by Django 3.0.14 on 2021-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(related_name='order', to='customer.MenuItem'),
        ),
    ]
